// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4J_hJbO6aasDV9wAwdwUXQLQ7I05z95M',
    appId: '1:752694225568:web:e34ee9d29106ef1ca2f7c5',
    messagingSenderId: '752694225568',
    projectId: 'encora-community-app',
    authDomain: 'encora-community-app.firebaseapp.com',
    storageBucket: 'encora-community-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8pirli-882ajeGqSmSma99Y55ZCvWdCE',
    appId: '1:752694225568:android:8fb0b360658bd6b2a2f7c5',
    messagingSenderId: '752694225568',
    projectId: 'encora-community-app',
    storageBucket: 'encora-community-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9Qvr4nCTeP_-ijMQJVRzV4bwXtqxjSOs',
    appId: '1:752694225568:ios:77a461c834cf71d4a2f7c5',
    messagingSenderId: '752694225568',
    projectId: 'encora-community-app',
    storageBucket: 'encora-community-app.firebasestorage.app',
    iosBundleId: 'com.example.encoraCommunity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9Qvr4nCTeP_-ijMQJVRzV4bwXtqxjSOs',
    appId: '1:752694225568:ios:77a461c834cf71d4a2f7c5',
    messagingSenderId: '752694225568',
    projectId: 'encora-community-app',
    storageBucket: 'encora-community-app.firebasestorage.app',
    iosBundleId: 'com.example.encoraCommunity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4J_hJbO6aasDV9wAwdwUXQLQ7I05z95M',
    appId: '1:752694225568:web:1c5b023eb4535128a2f7c5',
    messagingSenderId: '752694225568',
    projectId: 'encora-community-app',
    authDomain: 'encora-community-app.firebaseapp.com',
    storageBucket: 'encora-community-app.firebasestorage.app',
  );
}
